### ISSUE TITLE
Expiring Documents and Expired Documents Card Showing Static Values

### ISSUE THREAD

**Issue by fortune710** [fortune710/docguard#10]
## Description
Expired Documents and Expiring Documents Cards on home page show static values, and need to actually pull the count of expired and expiring documents from the DB. Expiring Documents are classified as documents that will expire in 6 months or less. The component holding the UI is a server component.

**Comment by MaestroDev19** [comment]
Done

**Comment by MaestroDev19** [comment]
![Screenshot 2024-05-23 120442](https://github.com/fortune710/docguard/assets/122155562/fdc65335-3133-489c-a6e1-5341923219b6)
done

**Comment by fortune710** [comment]
Nicely done!
